services:
  - type: web
    name: elevatta-fvs-medicao
    runtime: static
    buildCommand: echo "Elevatta FVS PWA Android 1.7.1"
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /sw.js
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
      - path: /index.html
        name: Cache-Control
        value: "no-cache, must-revalidate"
      - path: /version.json
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
      - path: /pwa.js
        name: Cache-Control
        value: "no-cache, must-revalidate"
      - path: /config.js
        name: Cache-Control
        value: "no-cache, must-revalidate"
      - path: /manifest.webmanifest
        name: Cache-Control
        value: "no-cache, must-revalidate"
      - path: /icons/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
